source 'https://rubygems.org'

gem 'bundler'
gem 'clamp'
gem 'stud'
gem 'did_you_mean'
gem 'minitest'
gem 'net-telnet'
gem 'power_assert'
gem 'rake'
gem 'rubygems-update'
gem 'test-unit'
gem 'xmlrpc'
gem 'github-auth'
gem 'pleaserun', :git => 'https://github.com/jordansissel/pleaserun.git'