- hosts: all
  connection: local
  become: yes 
  tasks:
    - name: debug
      become_user: "tg"
      vars:
        mypassword: "{{ lookup('community.general.passwordstore', 'ansible/workstation/' + username + ' missing=empty length=32 nosymbols=true') | default('123456', true) }}"
      debug: 
        var: mypassword

