---
- name: Install VNC packages
  become: yes
  package:
    name: "{{ vnc_package_name }}"
    state: present

- name: Create systemd service
  become: yes
  template:
    src: vncserver.service
    dest: /etc/systemd/system/vncserver@:1.service
    mode: 0744
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Create vnc config dir for user
  become: yes
  file:
    path: "{{ vnc_config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create user config
  become: yes
  template:
    src: vnc_config
    dest: "{{ vnc_config_dir }}/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  notify:
    - Restart vnc

- name: Create xstartup file
  become: yes
  template:
    src: xstartup
    dest: "{{ vnc_config_dir }}/xstartup"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  notify:
    - Restart vnc

- name: Check passwd file exists
  delegate_to: localhost
  stat:
    path: "{{ vnc_passwd_file }}"
  register: vnc_passwd_file

- name: Copy passwd file
  become: yes
  copy:
    src: "{{ vnc_passwd_file }}"
    dest: "{{ vnc_config_dir }}/passwd"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
  when: vnc_passwd_file.stat.exists

- name: Set VNC to start at boot
  become: yes
  systemd:
    daemon_reload: yes
    name: vncserver@:1
    state: started
    enabled: yes
