---
language: python
python: "2.7"
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  matrix:
    - MOLECULE_DISTRO: geerlingguy/docker-debian10-ansible
    - MOLECULE_DISTRO: geerlingguy/docker-debian9-ansible
    - MOLECULE_DISTRO: geerlingguy/docker-debian8-ansible
    - MOLECULE_DISTRO: geerlingguy/docker-centos7-ansible

install:
  - pip install testinfra ansible molecule ansible-apt docker
  - printf '[defaults]\nroles_path=../' >ansible.cfg # Create ansible.cfg with correct roles_path

script:
  - ansible --version
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
