- name: users | create group
  tags: groups,users
  become_user: "{{ username }}"
  group:
    name: "{{ username }}"
    state: present

- name: users | create user
  tags: sudo,users
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    groups: "{{ username }},users,{{ sudo_group }}"
    state: present
    comment: "user"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /usr/bin/zsh
    # shell: /usr/bin/nologin

- name: users | add sudoers file
  tags: settings,sudo,system,users
  command: "rm -f /etc/sudoers.d/{{ username }}; echo '{{ username }} ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/{{ username }}"
  # copy:
  #   src: "users/sudoers_{{ username }}"
  #   dest: "/etc/sudoers.d/{{ username }}"
  #   owner: root
  #   group: root
  #   mode: 0440

- name: users | create .ssh directory
  tags: dotfiles,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
  with_items:
    - { dir: "/home/{{ username }}/.ssh" }

- name: users | add all public keys
  tags: dotfiles,ssh,ssh-keys,users
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "users/{{ username }}/ssh/*.pub"
    # - "users/{{ username }}/ssh/*_id_ed25519.pub"

- name: Dotfiles - Get home directory
  user:
    name: "{{ username }}"
    state: present
  register: dotfiles_user_registered
  tags: dotfiles,users,barerepo

- name: Dotfiles - Set checkout if undefined
  set_fact:
    dotfiles_checkout: ['/*']
  when: dotfiles_checkout is undefined
  tags: dotfiles,users,barerepo

- name: Dotfiles - Check if directory exists
  stat:
    path: "{{ repo_dir }}"
  register: repo_directory
  tags: dotfiles,users,barerepo

- name: Git | Ensure bare repo is checked out
  become_user: "{{ username }}"
  git:
    repo: "{{ upstream }}"
    dest: "{{ repo_dir }}"
    version: "master"
    bare: yes
    track_submodules: yes
    recursive: yes
    force: yes
  when: not repo_directory.stat.exists
  tags: dotfiles,users,barerepo

- name: Git | Overwrite distro default dotfiles on the first run
  become_user: "{{ username }}"
  command: "git reset --hard"
  when: not repo_directory.stat.exists
  tags: dotfiles,users,barerepo
  # changed_when: "git_result.after|default('after') != git_result.before|default('before')"

# - name: Dotfiles - Clone repository
#   command: "git clone --bare {{ dotfiles_repo }} {{ repo_dir }}"
#   become: yes
#   become_user: "{{ username }}"
#   when: not repo_directory.stat.exists
#   tags: dotfiles,users,barerepo

# - name: Dotfiles - Update submodules
#   command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} -C {{ work_dir }} submodule update --init --recursive {{ item }}" # Git wants to cd into the directory first before using the submodule command
#   become: yes
#   become_user: "{{ username }}"
#   loop: "{{ dotfiles_checkout | map('regex_replace', '^.*\\/\\*', '~/') | list }}" # Recurse through all files/directories and attempt to recursively clone submodules. Just does nothing if there are none. Regex replace /* to ~/ for compatability with dotfiles_checkout.

- name: Dotfiles - Unset bare option to prevent fatal error (must be run in a work tree)
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local core.bare false"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: Dotfiles - Enable sparse checkout
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local core.sparseCheckout true"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: Dotfiles - Disable showing untracked files
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local status.showUntrackedFiles no"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

# Copy the dotfiles_checkout variable into a file for checkout
# - name: Dotfiles - Configure Git sparse checkout
#   copy:
#     dest: "{{ repo_dir }}info/sparse-checkout"
#     content: "{{ dotfiles_checkout | join('\n') }}"
#   become: yes
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo


# - name: Dotfiles - Checkout Git repository
#   command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} checkout --force" # This will overwrite existing files!
#   become: yes
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo

# - name: Dotfiles - Pull Git repository
#   command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} pull"
#   become: yes
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo

# - name: Dotfiles - Updating submodules
#   command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} submodule update -f --init --recursive"
#   become: yes
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo,update


# - name: Git | Ensure repository set properly
#   lineinfile: dest={{ repo_dir }}config
#               regexp="^\s*bare.?="
#               line="    bare = false"
#   tags: dotfiles,users,barerepo

# - name: Git | Ensure proper worktree
#   lineinfile: dest={{ repo_dir }}config
#               regexp='^\s*worktree.?='
#               line="    worktree = {{ work_dir }}"
#   tags: dotfiles,users,barerepo

# - name: Git | Ensure work dir
#   file: path={{ work_dir }} state=directory
#         mode=0775
#   tags: dotfiles,users,barerepo


# # fetch/checkout
# - name: Git | Fetching new changes
#   shell: chdir={{ repo_dir }} git fetch --prune && git fetch --tags
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo

# # - name: Git | Checkout version
# #   command: "chdir={{ work_dir }} git --git-dir={{ repo_dir }} checkout -f {{ version | default('HEAD') }}"
# #   become_user: "{{ username }}"
# #   tags: dotfiles,users,barerepo

# # - name: Git | Checkout dotfiles updates
# #   command: "chdir={{ work_dir }} git fetch && git checkout master && git merge upstream/master"
# #   become_user: "{{ username }}"
# #   tags: dotfiles,users,barerepo

# git submodules
# - name: Git | Submodules | Syncing
#   command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} submodule sync
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo,update

# - name: Git | Submodules | Updating
#   command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} submodule update -f --init --recursive
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo,update

# - name: Git | Ensure untracked files are hidden
#   command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} config --local status.showUntrackedFiles no
#   become_user: "{{ username }}"
#   tags: dotfiles,users,barerepo,update

- name: Git | Create symbolic link
  file:
    src: "{{ repo_dir }}"
    dest: "{{ work_dir }}.git"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: users | copy config directory
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.config/git/"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    ["users/{{ username }}/config/git/.gitconfig-personal", "users/{{ username }}/config/git/.gitconfig-hero", "users/{{ username }}/config/git/.gitconfig-company" ]

- name: users | copy config directory pass
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.config/pass-git-helper/"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    ["users/{{ username }}/config/pass-git-helper/git-pass-mapping.ini" ]

# - name: users | copy config directory
#   copy:
#     src: "{{ item }}"
#     dest: "/home/{{ username }}/.config"
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: 0644
#   with_fileglob:
#     - "users/{{ username }}/config/*"
#   tags: dotfiles,users,barerepo


- name: Dotfiles - Clone z-zsh
  stat:
    path: "/home/{{ username }}/z-zsh"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Checkout z-zsh repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/sjl/z-zsh.git"
    dest: "/home/{{ username }}/z-zsh"
    # update: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .vim
  stat:
    path: "/home/{{ username }}/.vim"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Checkout .vim repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/.vim.git"
    dest: "/home/{{ username }}/.vim"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone setup-keys
  stat:
    path: "/home/{{ username }}/setup-keys"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Checkout setup-keys repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/setup-keys.git"
    dest: "/home/{{ username }}/setup-keys"
    # update: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .oh-my-zsh
  stat:
    path: "/home/{{ username }}/.oh-my-zsh"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Checkout .oh-my-zsh repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ username }}/.oh-my-zsh"
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .oh-my-zsh-custom
  stat:
    path: "/home/{{ username }}/.oh-my-zsh-custom"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Checkout .oh-my-zsh-custom repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/oh-my-zsh-custom.git"
    dest: "/home/{{ username }}/.oh-my-zsh-custom"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone personal site
  stat:
    path: "/home/{{ username }}/site"
  register: subrepo_directory
  tags: dotfiles,users,submodules
- name: Git | Clone personal
  become_user: "{{ username }}"
  git:
    repo: "{{ site_upstream }}"
    dest: "/home/{{ username }}/site"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

# - name: Dotfiles - Clone personal blog
#   stat:
#     path: "/home/{{ username }}/blog"
#   register: subrepo_directory
#   tags: dotfiles,users,submodules
# - name: Git | Clone personal
#   become_user: "{{ username }}"
#   git:
#     repo: "{{ blog_upstream }}"
#     dest: "/home/{{ username }}/blog"
#     update: yes
#     track_submodules: yes
#     recursive: yes
#   when: not subrepo_directory.stat.exists
#   tags: dotfiles,users,submodules
