# - debug:
#     msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
#   when: ansible_default_ipv4.gateway is defined

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

# - name: Install browser package
#   vars:
#     browser_packages: "{{ lookup('file', 'browser_packages.txt').splitlines()|select('match', '^[^#]')|list }}"
#   with_items: "{{ browser_packages|default([]) }}"
#   when: item != ""
#   command: " {{ item }}"
#   changed_when: browser_package.rc != 1
#   failed_when: browser_package.rc > 1
#   register: browser_package
