- name: Create a directory if it does not exist
  file:
    path: /usr/share/backgrounds
    state: directory
    mode: '0755'

- name: gnome | appearance | copy lock screen and wallpaper background files
  tags: gnome,gnome-lockscreen
  become: true
  become_user: root
  with_items:
    - { src: "files/gnome/wallpaper-{{ username }}.png", dest: "/usr/share/backgrounds/default-wallpaper.png" }
    - { src: "files/gnome/lockscreen-{{ username }}.png", dest: "/usr/share/backgrounds/default-lockscreen.png" }
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# - name: Ensure pip3 is installed
#   package:
#     name: python-pip
#     state: present
#   become: yes
#   become_user: "{{ username }}"

# - name: Install psutil using pip
#   pip:
#     name: psutil
#     executable: pip
#   become: yes
#   become_user: "{{ username }}"

- name: gnome | configure defaults gnome shell
  tags: gnome,
  become_user: "{{ username }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/screensaver/picture-uri", value: "'file:///usr/share/backgrounds/default-lockscreen.png'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/default-wallpaper.png'" }
    - { key: "/org/gnome/desktop/background/picture-options", value: "'zoom'" }
    - { key: "/org/gnome/tweaks/show-extensions-notice", value: "false" }
    - { key: "/org/gnome/desktop/calendar/show-weekdate", value: "true" }
    - { key: "/org/gnome/desktop/datetime/automatic-timezone", value: "true" }
    - { key: "/org/gnome/desktop/interface/color-scheme", value: "'prefer-dark'" }
    - { key: "/org/gnome/desktop/interface/clock-show-date", value: "true" }
    - { key: "/org/gnome/desktop/interface/cursor-size", value: "'48'" }
    - { key: "/org/gnome/desktop/interface/text-scaling-factor", value: "'1/25'" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
    - { key: "/org/gnome/desktop/privacy/old-files-age", value: "uint32 5" }
    - { key: "/org/gnome/desktop/privacy/remember-app-usage", value: "false" }
    - { key: "/org/gnome/desktop/privacy/remember-recent-files", value: "false" }
    - { key: "/org/gnome/desktop/privacy/remove-old-temp-files", value: "true" }
    - { key: "/org/gnome/desktop/privacy/remove-old-trash-files", value: "true" }
    - { key: "/org/gnome/desktop/privacy/show-full-name-in-top-bar", value: "false" }
    - { key: "/org/gnome/desktop/wm/preferences/resize-with-right-button", value: "true" }
    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "':minimize,close'" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "false" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout", value: "'3600'" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type", value: "'nothing'" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout", value: "'1800'" }
    - { key: "/org/gnome/shell/app-switcher/current-workspace-only", value: "false" }
    - { key: "/org/gnome/software/refresh-when-metered", value: "true" }
    - { key: "/ca/desrt/dconf-editor/show-warning", value: "false" }
    - { key: "/org/gnome/software/first-run", value: "false" }
    - { key: "/org/gnome/boxes/first-run", value: "false" }
    - { key: "/org/gnome/terminal/legacy/Settings/theme-variant", value: "'dark'" }
    - { key: "/org/gnome/terminal/legacy/default-show-menubar", value: "false" }
    - { key: "/org/gnome/terminal/legacy/settings/confirm-close", value: "false" }
    - { key: "/org/gnome/swell-foop/first-run", value: "false" }
    - { key: "/org/gnome/nibbles/first-run", value: "false" }
    - { key: "/org/gnome/todo/first-run", value: "false" }
    - { key: "/org/gnome/desktop/sound/allow-volume-above-100-percent", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-panel/show-show-apps-button", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/isolate-monitors", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/preferred-monitor-by-connector", value: "'DP-0'" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-position", value: "'LEFT'" }
    - { key: "/org/gtk/Settings/FileChooser/sort-directories-first", value: "true" }
    - { key: "/org/gnome/shell/favorite-apps", value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'jetbrains-webstorm.desktop', 'sublime_text.desktop', 'arduino.desktop', 'librewolf.desktop', 'chromium.desktop', 'brave-browser.desktop', 'telegramdesktop.desktop', 'Ripcord.desktop']" }
    - { key: "/org/gnome/mutter/center-new-windows", value: "true" }
    - { key: "/org/gnome/mutter/workspaces-only-on-primary", value: "false" }
    - { key: "/org/gnome/mutter/dynamic-workspaces", value: "false" }
    
    # - { key: "/org/gnome/shell/enabled-extensions", value: "{{ gnome_enable_extensions|default([]) }}" }
