---

- name: Enable Gnome Shell extension
  become:      true
  become_user: "{{ username }}"
  command: "gnome-extensions enable {{ item }}"
  changed_when: enable_extension.rc != 1
  failed_when: enable_extension.rc > 1
  with_items: "{{ gnome_enable_extensions|default([]) }}"
  register: enable_extension
