---

- name: Parse Gnome Shell version
  become:      true
  become_user: "{{ username }}"
  shell: set -o pipefail && gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  args:
    executable: /usr/bin/bash
  register: r_gnome_extension_parse_shell_version
  changed_when: no

- name: Get Gnome Shell extension info
  become:      true
  become_user: "{{ username }}"
  vars:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"
  uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item.id }}&shell_version={{ gnome_shell_version }}
    return_content: yes
  with_items: "{{ gnome_extension_target|default([]) }}"
  register: r_gnome_extension_info


- include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
