---

#------------------------------------------------------------------------------------------------
- name: check if gnome shell extension is already installed
  become:      true
  become_user: "{{ username }}"
  stat:
    path: "{{ userhome }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
  register: r_gnome_extensions_check_existing
  changed_when: not r_gnome_extensions_check_existing.stat.exists



#------------------------------------------------------------------------------------------------
- block:

    - name: create temporary download directory
      tempfile:
        state: directory
        suffix: ".gnome_extension_download"
      become:       true
      become_user: "{{ username }}"
      register: r_gnome_extension_download_dir
      when: not r_gnome_extensions_check_existing.stat.exists

    - name: download gnome shell extension
      get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      become:       true
      become_user: "{{ username }}"
      register: r_gnome_extension_download

    - name: create install directory
      file:
        path: "{{ userhome }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0775

    - name: install gnome shell extension
      command: "gnome-extensions install --force {{ r_gnome_extension_download.dest }}"
      become:       true
      become_user: "{{ username }}"

    # - name: install gnome shell extension
    #   unarchive:
    #     src: "{{ r_gnome_extension_download.dest }}"
    #     dest: "{{ userhome }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
    #   become:       true
    #   become_user: "{{ username }}"


  always:
    - name: delete temporary download directory
      file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      become:       true
      become_user: "{{ username }}"


  when: not r_gnome_extensions_check_existing.stat.exists
