- name: Git | Clone gnome-macos-remap
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/petrstepanov/gnome-macos-remap"
    dest: "/home/{{ username }}/Downloads/gnome-macos-remap"
    force: yes
  tags: distro-setup

- name: gnome | keybindings | run install.sh script
  become_user: "{{ username }}"
  script: "/home/{{ username }}/Downloads/gnome-macos-remap/install.sh"
  tags: distro-setup

- name: gnome | keybindings | to undo "Flip Super and Control keys" restore backup
  tags: distro-setup
  copy:
    src: scripts/pc
    dest: /usr/share/X11/xkb/symbols/pc
    owner: root
    group: root
    mode: 0755
    force: true

- name: gnome | keybindings | set some personal preferences
  become_user: "{{ username }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/desktop/wm/keybindings/show-desktop", value: "'[]'" } # disable super+d shortcut