- name: gnome | peripherals | keyboard layout
  tags: gnome,keyboard,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us+intl')]"
    state: present

- name: gnome | peripherals | keyboard repeat interval
  tags: gnome,keyboard,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/repeat-interval"
    value: 15
    state: present

- name: gnome | peripherals | keyboard delay
  tags: gnome,keyboard,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/delay"
    value: 250
    state: present

- name: gnome | peripherals | numlock on by default
  tags: gnome,keyboard,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/numlock-state"
    value: "true"

- name: gnome | peripherals | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "false"

- name: gnome | peripherals | enable natural scrolling (touchpad)
  tags: gnome,mouse,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: gnome | peripherals | enable cursor acceleration (mouse)
  tags: gnome,mouse,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'adaptive'"

- name: gnome | peripherals | increase cursor speed (mouse)
  tags: gnome,mouse,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/speed"
    value: "-0.51"

- name: gnome | peripherals | increase cursor speed (touchpad)
  tags: gnome,mouse,peripherals
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/speed"
    value: "0.22"

- name: gnome | peripherals | set manual night-light schedule
  tags: gnome,peripherals,night-light
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "false"

# - name: gnome | peripherals | set manual night-light schedule start time
#   tags: gnome,peripherals,night-light
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
#     value: "23.0"

# - name: gnome | peripherals | set manual night-light schedule stop time
#   tags: gnome,peripherals,night-light
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
#     value: "7.4999999999999982"

# - name: gnome | peripherals | enable night-light
#   tags: gnome,peripherals,night-light
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
#     value: "true"

- name: gnome | peripherals | set power button behavior
  tags: gnome,peripherals,power
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'hibernate'"

# - name: gnome | peripherals | enable automatic suspend while plugged in to ac
#   tags: gnome,peripherals,power
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
#     value: "'suspend'"

- name: gnome | peripherals | set timeout for automatic suspend while plugged in to ac
  tags: gnome,peripherals,power
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "2700"

# - name: gnome | peripherals | enable automatic suspend while on battery
#   tags: gnome,peripherals,power
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
#     value: "'suspend'"

# - name: gnome | peripherals | set timeout for automatic suspend while plugged in to ac
#   tags: gnome,peripherals,power
#   become_user: "{{ username }}"
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
#     value: "1500"
