- name: Install packages
  vars:
    packages: "{{ lookup('file', 'packages.txt').splitlines()|select('match', '^[^#]')|list }}"
  with_items: "{{ packages }}"
  when: item != ""
  package: name={{ item }}

- name: Install AUR packages
  vars:
    aur_packages: "{{ lookup('file', 'packages_aur.txt').splitlines()|select('match', '^[^#]')|list }}"
  with_items: "{{ aur_packages }}"
  when: item != ""
  aur:
    name: "{{ item }}"

# sudo pip3 install defusedxml
