# [line_break]
# disabled = true

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
# [character]      # The name of the module we are configuring is "character"
# symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [env_var]
# variable = "SHELL"
# default = "unknown shell"

# prompt_order = [
#     "username",
#     "hostname",
#     "kubernetes",
#     "directory",
#     "git_branch",
#     "git_commit",
#     "git_state",
#     "git_status",
#     "hg_branch",
#     "package",
#     "dotnet",
#     "elm",
#     "golang",
#     "haskell",
#     "java",
#     "nodejs",
#     "php",
#     "python",
#     "ruby",
#     "rust",
#     "terraform",
#     "nix_shell",
#     "conda",
#     "memory_usage",
#     "aws",
#     "env_var",
#     "crystal",
#     "cmd_duration",
#     "line_break",
#     "jobs",
#     "battery",
#     "time",
#     "character",
# ]