#!/bin/bash

JETBRAINS_AGENT_DIR=$MY_DOTFILES/scripts/jetbrains-agent

function setup.jetbrains () {
	SYSTEM_VMOPTIONS_FILE=$1
	USER_VMOPTIONS_FILE=$2
	if [[ -e $SYSTEM_VMOPTIONS_FILE ]]; then
		
		alreadythere=0
		if [[ -e $USER_VMOPTIONS_FILE ]]; then
			alreadythere=$(grep "\-javaagent\:" ${USER_VMOPTIONS_FILE} | wc -l)
		fi
		if [ ${alreadythere} -eq 0 ]; then
			echo 'Installing'

			if [[ ! -d "${JETBRAINS_AGENT_DIR}" ]]; then
				mkdir -p $JETBRAINS_AGENT_DIR && git clone https://gitee.com/pengzhile/jetbrains-agent.git $JETBRAINS_AGENT_DIR
			fi
			
			echo 'Setting up'
			cp -i $SYSTEM_VMOPTIONS_FILE $USER_VMOPTIONS_FILE
			printf "\n\n-javaagent:${JETBRAINS_AGENT_DIR}/jetbrains-agent.jar" >> $USER_VMOPTIONS_FILE
			return 0
		else
			echo 'Already installed'
			return 1
		fi
	else
		echo "Error: File dont exist: ${SYSTEM_VMOPTIONS_FILE}"
		return 1
	fi
}

echo "License server: http://jetbrains-license-server"
# echo "http://jetbrains-license-server" | pbcopy
cat "${JETBRAINS_AGENT_DIR}/ACTIVATION_CODE.txt" | pbcopy

if setup.jetbrains /Applications/WebStorm.app/Contents/bin/webstorm.vmoptions ~/Library/Preferences/WebStorm2019.1/webstorm.vmoptions; then
	open -a WebStorm
fi

# if setup.jetbrains /Applications/PhpStorm.app/Contents/bin/phpstorm.vmoptions ~/Library/Preferences/PhpStorm2018.3/phpstorm.vmoptions; then
# 	open -a PhpStorm
# fi

# if setup.jetbrains /Applications/PyCharm.app/Contents/bin/pycharm.vmoptions ~/Library/Preferences/PyCharm2019.1/pycharm.vmoptions; then
# 	open -a PyCharm
# fi
