- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: "ansible provision"
    user: velociraptor
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "{ date; /usr/local/bin/provision; RC=$?; date; echo \"Exit code: $RC\"; } >> /var/log/ansible_provision.log 2>&1 && if [ $RC -eq 0 ]; then echo $(date) > /var/log/ansible_provision_last_run.txt; fi"

# - name: system setup | cron | close process everyday
#   tags: cron
#   cron:
#     name: "close process everyday"
#     user: "{{ username }}"
#     hour: "7"
#     minute: "0"
#     job: "top -p $(pgrep -d',' httpd) > /dev/null"

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: velociraptor
    special_time: reboot
    job: "/bin/rm -rf /home/{{ username }}/.ansible ~/.ansible"
