- name: system setup | scripts | copy image_prep.sh script
  tags: scripts
  copy:
    src: system_setup/image_prep.sh
    dest: /usr/local/bin/image_prep.sh
    owner: root
    group: root
    mode: 0755
