name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it- uses: actions/c
    - uses: actions/checkout@master
    -
      name: Checkout
      uses: actions/checkout@v3
    # - 
    #   name: Configure GPG Key
    #   run: |
    #     echo -n "${CI_GPG_SIGN_KEY}" | base64 --decode | gpg --import
    #   env:
    #     CI_GPG_SIGN_KEY: ${{ secrets.CI_GPG_SIGN_KEY }}
    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: "${{ secrets.CI_GPG_SIGN_KEY }}"
        passphrase: "${{ secrets.CI_GPG_PASSPHRASE }}"
    -
      name: List keys
      run: |
        gpg -K
        git clone "https://github.com/thomasgroch/password-store-for-testing.git" ~/.password-store
        wget https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass_1.14.3_linux_amd64.deb
        sudo dpkg -i gopass_1.14.3_linux_amd64.deb
        gopass show "ansible/workstation/runner"
        
    - 
      name: Run bootstrap
      run: |
        gpg --list-secret-keys
        gpg2 --list-secret-keys
        ./bootstrap.sh "https://github.com/thomasgroch/password-store-for-testing.git" "tg"
      env:
        WORKSPACE_PATH: ${{github.workspace}} # "/home/runner/work/dotfiles/dotfiles"
        DOTFILES_REF: ${{github.sha}} # "8acd4815dfe44ee26810b01e6a0129f13781480a"